

*   Họ Tên: Huỳnh Thiện Tùng
*   MSSV: 19522492
*   Bài tập 9




# Import thư viện

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [2]:
!gdown --id 1cxt5PYGe38O-cjn4MXJ5JH3V24NbVnSQ

Downloading...
From: https://drive.google.com/uc?id=1cxt5PYGe38O-cjn4MXJ5JH3V24NbVnSQ
To: /content/50_Startups.csv
100% 2.44k/2.44k [00:00<00:00, 2.10MB/s]


# Đọc và khám phá dữ liệu

In [3]:
df = pd.read_csv('50_Startups.csv')
df.head(10)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94
5  131876.90        99814.71        362861.36    New York  156991.12
6  134615.46       147198.87        127716.82  California  156122.51
7  130298.13       145530.06        323876.68     Florida  155752.60
8  120542.52       148718.95        311613.29    New York  152211.77
9  123334.88       108679.17        304981.62  California  149759.96

In [5]:
#  Encoding categorical data
transformer = ColumnTransformer(
    transformers=[
        ("State",
         OneHotEncoder(),
         [3]              # country column or the column on which categorical operation to be performed
         )
    ],
    remainder='passthrough'
)

X = transformer.fit_transform(df.to_numpy())

print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1 192261.83]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53 191792.06]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54 191050.39]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62 182901.99]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42 166187.94]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36 156991.12]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82 156122.51]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68 155752.6]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29 152211.77]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62 149759.96]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95 146121.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55 144259.4]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44 141585.52]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93 134307.35]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92 132602.65]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23 129917.04]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06 126992.93]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31 125370.37]
 [0.0 1.0 0.0 91749.16 1

In [6]:
pd.options.display.float_format = '{:,.2f}'.format
df = pd.DataFrame(X, columns=["State (California)", "State (Florida)",  
                         "State (New York)", "R&D Spend", 
                         "Administration", "Marketing", "Profit"])
df.head(10)

State (California) State (Florida)  ...  Marketing     Profit
0               0.00            0.00  ... 471,784.10 192,261.83
1               1.00            0.00  ... 443,898.53 191,792.06
2               0.00            1.00  ... 407,934.54 191,050.39
3               0.00            0.00  ... 383,199.62 182,901.99
4               0.00            1.00  ... 366,168.42 166,187.94
5               0.00            0.00  ... 362,861.36 156,991.12
6               1.00            0.00  ... 127,716.82 156,122.51
7               0.00            1.00  ... 323,876.68 155,752.60
8               0.00            0.00  ... 311,613.29 152,211.77
9               1.00            0.00  ... 304,981.62 149,759.96

[10 rows x 7 columns]

In [7]:
df.tail(5)

State (California) State (Florida)  ...  Marketing    Profit
45               0.00            0.00  ...   1,903.93 64,926.08
46               0.00            1.00  ... 297,114.46 49,490.75
47               1.00            0.00  ...       0.00 42,559.73
48               0.00            0.00  ...       0.00 35,673.41
49               1.00            0.00  ...  45,173.06 14,681.40

[5 rows x 7 columns]

In [8]:
X = df.iloc[:, :6].to_numpy()
y = df.loc[:, "Profit"].to_numpy().reshape(-1, 1)

In [9]:
print(X.shape)
print(y.shape)

(50, 6)
(50, 1)


In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

(40, 6)
(40, 1)
(10, 6)
(10, 1)


# Linear Regression Model

In [11]:
model = LinearRegression()
model.fit(X_train, y_train)

y_predict = model.predict(X_test)

In [12]:
print("Coefficients: \n", model.coef_)
print("Mean squared error: %.2f" % mean_squared_error(y_test, y_predict))
print("Coefficient of determination: %.2f" % r2_score(y_test, y_predict))

Coefficients: 
 [[-3.15260255e+02  6.23532751e+02 -3.08272495e+02  8.05630064e-01
  -6.87878823e-02  2.98554429e-02]]
Mean squared error: 82010363.05
Coefficient of determination: 0.90


# Dùng KFold

In [13]:
k = 5
kf = KFold(n_splits=k, random_state=None)
model = LinearRegression()
# using negative MSE
score = cross_val_score(model, X , y, scoring='neg_mean_squared_error', cv = kf)
print("Score = ", score)
print("Negative MSE = ", score.mean())

Score =  [-3.19757405e+07 -1.31773822e+08 -3.80623882e+07 -7.47211906e+07
 -2.39539562e+08]
Negative MSE =  -103214540.65469384
