

*   Họ Tên: Huỳnh Thiện Tùng
*   MSSV: 19522492
*   Bài tập 9




# Import thư viện

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import StandardScaler

In [2]:
!gdown --id 1GUyjOSe1aYziNZUJ3apv0vsG2YaB6_nZ

Downloading...
From: https://drive.google.com/uc?id=1GUyjOSe1aYziNZUJ3apv0vsG2YaB6_nZ
To: /content/Churn_Modelling.csv
100% 685k/685k [00:00<00:00, 42.7MB/s]


# Đọc và khám phá dữ liệu

In [3]:
df = pd.read_csv('/content/Churn_Modelling.csv')
df.head(10)

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0
5          6    15574012       Chu  ...               0       149756.71      1
6          7    15592531  Bartlett  ...               1        10062.80      0
7          8    15656148    Obinna  ...               0       119346.88      1
8          9    15792365        He  ...               1        74940.50      0
9         10    15592389        H?  ...               1        71725.73      0

[10 rows x 14 columns]

# Chuyển đổi giá trị rời rạc sang one hot encoder

Lấy những cột cần thiết

In [4]:
X = df.iloc[:, 3:-1]
y = df.iloc[:, -1]
X = pd.get_dummies(data=X, columns=['Geography', 'Gender'])

In [5]:
X

CreditScore  Age  Tenure  ...  Geography_Spain  Gender_Female  Gender_Male
0             619   42       2  ...                0              1            0
1             608   41       1  ...                1              1            0
2             502   42       8  ...                0              1            0
3             699   39       1  ...                0              1            0
4             850   43       2  ...                1              1            0
...           ...  ...     ...  ...              ...            ...          ...
9995          771   39       5  ...                0              0            1
9996          516   35      10  ...                0              0            1
9997          709   36       7  ...                0              1            0
9998          772   42       3  ...                0              0            1
9999          792   28       4  ...                0              1            0

[10000 rows x 13 columns]

In [6]:
X = X.values
X

array([[619.,  42.,   2., ...,   0.,   1.,   0.],
       [608.,  41.,   1., ...,   1.,   1.,   0.],
       [502.,  42.,   8., ...,   0.,   1.,   0.],
       ...,
       [709.,  36.,   7., ...,   0.,   1.,   0.],
       [772.,  42.,   3., ...,   0.,   0.,   1.],
       [792.,  28.,   4., ...,   0.,   1.,   0.]])

In [7]:
y = y.values.reshape(-1, 1)
y

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [0]])

Chia train/test

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
print(X_train.shape)
print(y_train.shape)

print(X_test.shape)
print(y_test.shape)

(8000, 13)
(8000, 1)
(2000, 13)
(2000, 1)


# Chuẩn hóa dữ liệu sử dụng StandardScaler

In [10]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_train

array([[ 0.35649971, -0.6557859 ,  0.34567966, ..., -0.57638802,
        -0.91324755,  0.91324755],
       [-0.20389777,  0.29493847, -0.3483691 , ..., -0.57638802,
        -0.91324755,  0.91324755],
       [-0.96147213, -1.41636539, -0.69539349, ...,  1.73494238,
        -0.91324755,  0.91324755],
       ...,
       [ 0.86500853, -0.08535128, -1.38944225, ..., -0.57638802,
         1.09499335, -1.09499335],
       [ 0.15932282,  0.3900109 ,  1.03972843, ..., -0.57638802,
        -0.91324755,  0.91324755],
       [ 0.47065475,  1.15059039, -1.38944225, ..., -0.57638802,
        -0.91324755,  0.91324755]])

In [33]:
n_features = X_train.shape[1]
# define the keras model
model = Sequential()
model.add(Dense(6, input_dim=n_features, activation='relu'))
model.add(Dense(6, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [34]:
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# K Fold

In [ ]:
k = 5
size = X_train.shape[0] // k
size2 = X_test.shape[0] // k
pos = 0
pos2 = 0
acc = []
for i in range(k):
    X_subset_train = X_train[pos:(i+1) * size, :]
    y_subset_train = y_train[pos:(i+1) * size, :]

    X_subset_test = X_test[pos2:(i+1) * size2, :]
    y_subset_test = y_test[pos2:(i+1) * size2, :]

    pos = (i+1)*size
    pos2 = (i+1)*size2

    model.fit(X_subset_train, y_subset_train, epochs=100, batch_size=128)
    _, accuracy = model.evaluate(X_subset_test, y_subset_test)
    acc.append(accuracy)

Epoch 1/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5078 - accuracy: 0.7987
Epoch 2/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5062 - accuracy: 0.7981
Epoch 3/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5026 - accuracy: 0.7987
Epoch 4/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5020 - accuracy: 0.7987
Epoch 5/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5028 - accuracy: 0.7975
Epoch 6/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5046 - accuracy: 0.7987
Epoch 7/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5030 - accuracy: 0.7987
Epoch 8/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5011 - accuracy: 0.7994
Epoch 9/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5011 - accuracy: 0.7987
Epoch 10/100
13/13 [==============================] - 0s 2ms/step - loss: 0.5011 - accuracy: 0.7987
Epoch 11/

In [ ]:
for i, accuracy in enumerate(acc):
    print(f"K = {i+1}: ===============> accuracy: {accuracy}")
print("Mean: {:.2f} %".format(np.mean(acc) * 100))

K = 1: ===============> accuracy: 0.8025000095367432
K = 2: ===============> accuracy: 0.800000011920929
K = 3: ===============> accuracy: 0.8224999904632568
K = 4: ===============> accuracy: 0.7925000190734863
K = 5: ===============> accuracy: 0.800000011920929
Mean: 80.35 %


# Evaluate

Thử nghiệm xem với khách hàng có thông tin sau thì có nên exit hay ko?

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: $ 60000

No.of Products: 2

Has credit card: Yes

Active Member: Yes

Estimated Salary: $50000

In [37]:
customer = [[600, 40, 3, 60000, 2, 1, 1, 50000, 1, 0, 0, 0, 1]]

In [38]:
predictions = (model.predict(customer) > 0.5).astype(int)
predictions

array([[1]])